#7-base_geometry

================================
Test file for 7-base_geometry.py
================================

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()
>>> bg.area()
Traceback (most recent call last):
	...
Exception: area() is not implemented


>>> bg = BaseGeometry()
>>> bg.integer_validator("name", 31)
>>>

>>> bg = BaseGeometry()
>>> bg.integer_validator("width", -2)
Traceback (most recent call last):
	...
ValueError: width must be greater than 0


>>> bg = BaseGeometry()
>>> bg.integer_validator("height", 0)
Traceback (most recent call last):
        ...
ValueError: height must be greater than 0


>>> bg = BaseGeometry()
>>> bg.integer_validator("name", "a")
Traceback (most recent call last):
        ...
TypeError: name must be an integer


>>> bg = BaseGeometry()
>>> bg.integer_validator()
Traceback (most recent call last):
        ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg = BaseGeometry()
>>> bg.integer_validator("my_value")
Traceback (most recent call last):
        ...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> bg = BaseGeometry()
>>> bg.integer_validator("name", True)
Traceback (most recent call last):
	...
TypeError: name must be an integer


>>> bg.integer_validator("name", 5j)
Traceback (most recent call last):
	...
TypeError: name must be an integer


>>> bg.integer_validator("name", 7, 2)
Traceback (most recent call last):
	...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.area(10)
Traceback (most recent call last):
	...
TypeError: area() takes 1 positional argument but 2 were given

>>> bg.integer_validator("name", None)
Traceback (most recent call last):
	...
TypeError: name must be an integer

>>> bg.integer_validator("name", [1, 2])
Traceback (most recent call last):
	...
TypeError: name must be an integer

>>> bg.integer_validator("name", (5,))
Traceback (most recent call last):
	...
TypeError: name must be an integer

>>> bg.integer_validator("name", {"age": 10})
Traceback (most recent call last):
	...
TypeError: name must be an integer

>>> bg.area(8, 9)
Traceback (most recent call last):
	...
TypeError: area() takes 1 positional argument but 3 were given


