# 101-lazy_matrix_mul

===============================
test file for 101-lazy_matrix_mul.py
===============================

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> lazy_matrix_mul([])
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> lazy_matrix_mul([], [])
0.0

>>> lazy_matrix_mul([[]], [[]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (1,0) not aligned: 0 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[1, 'b'], [2, 3]], [['a', 5], [7, 9]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[1, 2], [2, 3]], [[3, 5], [7, 9], [4, 2]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

>>> lazy_matrix_mul()
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> lazy_matrix_mul([[1, 2, 3]], [[3, 5, 9]])
Traceback (most recent call last):
ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[0, 0], [0, 0]], [[0, 0], [0, 0]])
[[0, 0], [0, 0]]

>>> lazy_matrix_mul([[2.1, 3.5], [-6, -8.3]], [[7.4, 9.4], [-7, -1.2]])
[[-8.96, 15.54], [13.7, -46.44]]

>>> lazy_matrix_mul([[1, 2, 3], [4, 5]], [[6, 7], [8, 9]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul("i'am a matrix", [[6, 7], [8, 9]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([[1, 2, 3]], "i'am a matrix")
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([1, 2, 3], [[2, 3, 5], [5, 9, 7]])
Traceback (most recent call last):
ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

>>> lazy_matrix_mul([[2, 3, 5], [5, 9, 7]], [1, 2, 3])
array([23, 44])

>>> lazy_matrix_mul([[2, 3, 5], [5, 9, 7]], [])
Traceback (most recent call last):
ValueError: shapes (2,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)

>>> lazy_matrix_mul([[2, 3, 5], [5, 9, 7]], [['a', 'b', 'c'], ['d', 'e', 'f']])
Traceback (most recent call last):
ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2, 3], [4, 5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
